import { BASE_URL } from './Base';

// URL
export const URL_POKEDEX = `${BASE_URL}/pokemon/`;

// Types
export const types = {
   POKEDEX_LOADING: 'POKEDEX_LOADING',
   POKEDEX_SUCCESS: 'POKEDEX_SUCCESS',
   POKEDEX_FAILED: 'POKEDEX_FAILED',

   POKEDEX_MORE_LOADING: 'POKEDEX_MORE_LOADING',
   POKEDEX_MORE_SUCCESS: 'POKEDEX_MORE_SUCCESS',
   POKEDEX_MORE_FAILED: 'POKEDEX_MORE_FAILED',
};
